### ISSUE TITLE
MP3 is missing and not working

### ISSUE THREAD

**Issue by ghost** [flathub/org.olivevideoeditor.Olive#11]
# #
![Screenshot from 2020-06-30 11-46-17](https://user-images.githubusercontent.com/67544305/86417601-fe078280-bcbc-11ea-8342-fd4a602c1730.png)

it gives me an unknown codec

**Comment by ghost** [comment]
Reminder I have the MP3 and other codec install and both snap and appimage show MP3 but not the flatpak 

> ![Screenshot from 2020-06-30 11-46-17](https://user-images.githubusercontent.com/67544305/86417601-fe078280-bcbc-11ea-8342-fd4a602c1730.png)
> 
> it gives me an unknown codec

**Comment by eszlari** [comment]
This is fixed now, but why use MP3?
