### ISSUE TITLE
Weird issue since last commit

### ISSUE THREAD

**Issue by okseb** [flathub/org.olivevideoeditor.Olive#3]
Not sure if this issue is Flatpak specific but I though to try here before creating an issue on the main repo, the issue is screenshotted below but previews are no longer rendering properly.

![screenshot from 2019-03-03 00-44-49](https://user-images.githubusercontent.com/13012832/53691531-dd888a80-3d4d-11e9-94e8-21178e535165.png)

**Comment by eszlari** [comment]
Should be fixed.

**Comment by okseb** [comment]
Yeah it's fixed thanks for the quick update.
